name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  token:
    description: 'Github token'
    required: true
  title:
    description: 'Issue title'
    required: true
  body:
    description: 'Github body'
  assignees:
    description: 'Issue Assignees'

# Define your outputs here.
outputs:
  issue:
    description: 'Your issue object as a json string'

runs:
  using: node20
  main: dist/index.js
